import Head from 'next/head';
import styles from '@/styles/Home.module.sass';
import { useState } from 'react';

export default function Home() {
	const [username, setUsername] = useState('');
	const [password, setPassword] = useState('');

	return (
		<>
			<Head>
				<title>Login</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>
			<main className={`d-flex justify-content-center align-items-center ${styles.main}`}>
				<div className={`card ${styles.w300px} ${styles.h200px}`}>
					<div className="card-header fs-3 fw-bold">Login</div>
					<div className="card-body">
						<input
							type="text"
							value={username}
							onChange={e => setUsername(e.currentTarget.value)}
							className="form-control mb-3"
							placeholder="Username" />
						<input
							type="password"
							value={password}
							onChange={e => setPassword(e.currentTarget.value)}
							className="form-control"
							placeholder="Password" />
					</div>
					<div className="card-footer d-flex">
						<div
							onChange={}
							className="btn btn-primary ms-auto">Log In</div>
					</div>
				</div>
			</main>
		</>
	);
}
